sudo: false

language: node_js
node_js:
  - 10

script: npm run build --modern

branches:
  only:
    - develop

deploy:
  provider: pages
  github-token:
    secure: KyXQqTLhdZTwtwTMNZmQY9heY84qeXpTT9jH3bpfCRlVUnftzmdl2ATTd+1cJjO3IMKWv1gvNNN+tSbdyvKOahpWAWF/R4hBj4cK5RoJ/XXyu6UiKtF/zW1cZZLE51l7DdJfy5gqstd+fcHt/uz1et103lq2Ox8nJ3HgH/JKqayO0KYyPh2ovo059PMYouFGmd8Ys6SSEgBtfgvivKRaWlBlonqzOP8ImigErawEdltL7CWIW7KFnXGq9A9UjR/f+4dkhEyO61i4VNoe7hKD6au3qgXimD47P4ASG5Ndpn90kKs6VPQ5dfMNIlLN2peXmouVr4Wm/kCYBZusegziyf0mSqXm500xYkw+gpSMjBzjzDGMK/Ovu3akK2eOMWGVDTM8R5b1gahcwblTy2Rwg5N99Qp1Fdymb2vRL+iEXeCNAKfZXpPHm2rFYMU0FVhv562rdFDb2FJboFTLopGa84bFzLe8Np1sqvbC8lxDp7HaBeugvW0wK7JsVgv1aMPdwjkNi5LXlhN9LGgfeN82aIbsocmElM1FOVsHi5E49uBDCQNrzMmqM4GpH1IJXtl2wyk9+LDTe1bvfTto4vTC0zWrKyrjVCkFv0z5Jkk4dCJMWHQNb4X2WQs/NO6mBLqCGKiY9pMAw/E2e5lW4KoQM1Hc3pc62yS/h2RNLzxWGS0=
  skip-cleanup: true
  local-dir: dist
  target_branch: master
  on:
    branch: develop
