<template>
  <div id="app">
    <b-jumbotron fluid tag="section">
      <Profile :name="name" :email="email" :accounts="accounts"></Profile>
    </b-jumbotron>
    <div class="container-fluid">
      <FeedList :feedUrls="feedUrls"></FeedList>
    </div>
    <footer class="text-center">
      <small class="text-muted">&copy; 2018 {{ name }} | The robot is generated by
        <a href="https://robohash.org/" target="_blank" class="text-muted">Robohash.org</a>
      </small>
    </footer>
  </div>
</template>

<script>
import Profile from './components/Profile.vue';
import FeedList from './components/FeedList.vue';

export default {
  name: 'app',
  data() {
    return {
      name: process.env.VUE_APP_NAME,
      email: process.env.VUE_APP_EMAIL,
      accounts: [
        {
          name: 'Twitter',
          url: `https://twitter.com/${process.env.VUE_APP_TWITTER_USERNAME}`,
        },
        {
          name: 'GitHub',
          url: `https://github.com/${process.env.VUE_APP_GITHUB_USERNAME}`,
        },
        {
          name: 'Hatena',
          url: 'http://profile.hatena.ne.jp/fuji-nakahara/',
        },
        {
          name: 'カクヨム',
          url: 'https://kakuyomu.jp/users/fuji-nakahara',
        },
        {
          name: 'amakan',
          url: `https://amakan.net/@${process.env.VUE_APP_TWITTER_USERNAME}`,
        },
      ],
      feedUrls: [
        'https://fuji-nakahara.hatenablog.com/feed',
        'https://fuji-nakahara.github.io/genron-sf-2018/feed.xml',
        'https://fuji-nakahara.github.io/cyborg-classmate/feed.xml',
      ],
    };
  },
  components: {
    Profile,
    FeedList,
  },
};
</script>
