<template>
  <div id="app">
    <b-jumbotron
      fluid
      tag="section"
    >
      <TheProfile
        :name="name"
        :email="email"
        :accounts="accounts"
      />
    </b-jumbotron>
    <div class="container-fluid">
      <TheFeedList
        :feedUrls="feedUrls"
        v-on:enter-feed="showFooter = true"
      />
      <transition
        appear
        enter-active-class="animated fadeIn"
      >
        <footer
          v-show="showFooter"
          class="text-center mb-3"
        >
          <small class="text-muted">
            &copy; 2018 {{ name }} | The robot is generated by
            <a
              href="https://robohash.org/"
              target="_blank"
              class="text-muted"
            >
              Robohash.org
            </a>
          </small>
        </footer>
      </transition>
    </div>
  </div>
</template>

<script>
import TheProfile from './components/TheProfile.vue';
import TheFeedList from './components/TheFeedList.vue';

export default {
  name: 'app',
  data() {
    return {
      showFooter: false,
    };
  },
  components: {
    TheProfile,
    TheFeedList,
  },
};
</script>
